import pandas as pd
from pandas import Series,DataFrame
import numpy as np
import matplotlib as plt
df=pd.read_csv('train.csv')
print df.head(10)
print df.describe()
print df['Age'].median()
print df['Sex'].unique()
print df['Embarked'].unique()
# Distribution analysis
fig=plt.pyplot.figure(figsize=(8,4))
ax=fig.add_subplot(121)
ax.hist(df['Age'],bins=10,range=(df['Age'].min(),df['Age'].max()))
plt.pyplot.title('Age distribution')
plt.pyplot.xlabel('Age')
plt.pyplot.ylabel('Count of Passengers')
plt.pyplot.show()

ax = fig.add_subplot(122)
ax.hist(df['Fare'], bins = 10, range = (df['Fare'].min(),df['Fare'].max()))
plt.pyplot.title('Fare distribution')
plt.pyplot.xlabel('Fare')
plt.pyplot.ylabel('Count of Passengers')
plt.pyplot.show()
#categorical variable analysis
temp1=df.groupby('Pclass').Survived.count()
temp2=df.groupby('Pclass').Survived.sum()/df.groupby('Pclass').Survived.count()
fig=plt.pyplot.figure(figsize=(8,4))
ax1 = fig.add_subplot(121)
ax1.set_xlabel('Pclass')
ax1.set_ylabel('Count of Passengers')
ax1.set_title("Passengers by Pclass")
temp1.plot(kind='bar')
ax2=fig.add_subplot(122)
temp2.plot(kind='bar')
ax2.set_xlabel('Pclass')
ax2.set_ylabel('Probability of Survival')
ax2.set_title("Probability of survival by class")

a=df.groupby('Sex').Survived.count()
b=df.groupby('Sex').Survived.sum()/df.groupby('Sex').Survived.count()
fig = plt.pyplot.figure(figsize=(8,4))
ax3 = fig.add_subplot(121)
ax3.set_xlabel('Sex')
ax3.set_ylabel('Count of Passengers')
ax3.set_title("Passengers by Sex")
a.plot(kind='bar')

ax4 = fig.add_subplot(122)
b.plot(kind = 'bar')
ax4.set_xlabel('Sex')
ax4.set_ylabel('Probability of Survival')
ax4.set_title("Probability of survival by Sex")
temp3 = pd.crosstab([df.Pclass, df.Sex,df.Embarked], df.Survived.astype(bool))
temp3.plot(kind='bar', stacked=True, color=['red','blue','green'], grid=False)
